language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.2
  - android-28
  - sys-img-x86-android-28
  - sys-img-armeabi-v7a-google_apis-28
  - sys-img-armeabi-v7a-addon-google_apis-google-28
  licences:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_script:
  - mkdir -p "$ANDROID_HOME/licenses"
before_install:
  - yes | sdkmanager "platforms;android-28"
script:
  - ./gradlew assembleDebug
